### diff helper_image VS docker image
# concurrent = 1
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "via docker"
  url = "http://localhost"
  id = 13
  token = "glrt-2GR51rubUbopK_fqMFLz"
  token_obtained_at = 2023-12-12T14:51:21Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  # only docker image:
  environment = ["DOCKER_DRIVER=overlay2", "DOCKER_LOGIN=gitlab-ci", "DOCKER_PASSWORD=password"]
  [runners.cache]     
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    # image = ""
    image = "docker:latest"
    # privileged = true
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    # volumes = ["/certs/client", "/cache"]
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    shm_size = 0
    network_mode = "host"
    # helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:x86_64-e0218c92"
    # network_mtu = 0
    # only docker image:
    pull_policy = ["always", "if-not-present"]

